### PR TITLE
Update firmware for USB MSD boot

### PR DESCRIPTION
**Pull request by timg236**
firmware: c1dc0385792777ef847939780350417a42e700fb

### CODE REVIEW

**Comment by timg236** [comment]
@popcornmix Looks as though I can't request a new branch via pull request.  Please can you pull this into msd-boot

**Comment by tonyfoxley** [comment]
may i have this please

**Comment by timg236** [comment]
no

**Comment by timg236** [comment]
The firmware update will go into the master rpi-update branch via the usual route

**Pull request closed without merging**
