### PR TITLE
Fix typos (mostly in comments and documentation)

### PR DESCRIPTION
**Pull request by stweil**
Most of them were found and fixed using codespell.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by 6by9** [comment]
Almost all of those are files exported from the firmware source, so can't be updated via a pull request (all the changes would be overwritten with the next update).
I'll go through your changes to make the corresponding mods to the firmware source.

**Comment by stweil** [comment]
@6by9, is that firmware source also available on GitHub (so I could help you with the changes)?

**Comment by 6by9** [comment]
No, it's the closed source code to build start.elf/start_x.elf.

**Comment by popcornmix** [comment]
Thanks - this should now be present in firmware and userland repos.

**Comment by 6by9** [comment]
@stweil  If you've still got codespell set up, could you rerun it on the updated headers? Thanks.

**Comment by stweil** [comment]
@6by9: Done. See also https://github.com/raspberrypi/userland/pull/299.

**Comment by 6by9** [comment]
Thanks.

As previously commented, all those in OMX_*.h come from upstream Khronos headers so I'm not going to fix those.
The html docs come from the source files within the firmware via a magic script. I thought I'd fixed all of those in the firmware source, but seeing as the docs directory hasn't been updated for 2 years I guess the scripts hasn't been run.

That leaves ilclient. I'm not sure whether that is being pulled in from the firmware source tree by script or some other means. I'll look at fixing it up there in the first instance anyway.

**Comment by 6by9** [comment]
I'm being silly. The ilclient header is a build result from hello_pi in userland. That needs fixing and will fix this one.
So just the IL docs to get updated - now can I remember the runes to run the script?

**Comment by popcornmix** [comment]
I've cherry-picked most of these. Can you rebase and see if anything is missed (excluding the files that originated from upstream).

**Comment by stweil** [comment]
There remain only files named OMX_*.h after rebasing, so it looks like you picked all relevant ones. Thanks.

**Comment by popcornmix** [comment]
Okay thanks.

**Pull request closed without merging**
