### PR TITLE
Update the description for i2c_gpio_delay_us

### PR DESCRIPTION
**Pull request by davesliu**
The description of default value shall be  5 that related to ~100kHZ
According to the i2c_gpio_probe() of i2c-gpio.c

### CODE REVIEW

**Comment by davesliu** [comment]
See detail in https://github.com/raspberrypi/linux/blob/3ed6d34d53e94ecbebc64c8fa3d1b6d3c41db8fb/drivers/i2c/busses/i2c-gpio.c#L428

**Comment by popcornmix** [comment]
The file here is just copied from https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/README
The PR should go to the linux repo.

**Comment by pelwell** [comment]
The README is correct: https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/overlays/i2c-gpio-overlay.dts#L20

**Comment by davesliu** [comment]
@pelwell  Thanks for your correction.
 :-)

**Pull request closed without merging**
