### PR TITLE
Typo in overlays Readme

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by pelwell** [comment]
Good spot, but this is the wrong place to fix it since it is copied verbatim from the rpi Linux source tree.

**Comment by popcornmix** [comment]
To clarify this is the file that needs fixing: https://github.com/raspberrypi/linux/blob/rpi-4.1.y/arch/arm/boot/dts/overlays/README#L490
The firmware version gets copied when a new firmware is built.

**Comment by lurch** [comment]
Ahh, thanks for the correction!
Unfortunately when I click on the "edit this file" pencil-icon in the Github web interface for the linux repo, it just tells me "This blob took too long to generate." and I'm afraid I don't have the time to set up a local clone and do a command-line PR right now :-/
I'll create the Linux-PR on Saturday, if you haven't already manually fixed it by then.

**Comment by pelwell** [comment]
It's OK - I'll fix it.

**Comment by lurch** [comment]
Cheers Phil :)

**Comment by pelwell** [comment]
This change got rolled into https://github.com/raspberrypi/linux/commit/9f160c14d58a393a160f24f528d238ef44565e61, https://github.com/raspberrypi/linux/commit/b7bbcabcce3f31bca25f17d68fb9eb0e2e045184 and https://github.com/raspberrypi/linux/commit/00fffdec1d020c7f6d8f07bfe9e644b4760a65ba.

**Pull request closed without merging**
