### PR TITLE
backup-switchover-mode value definitions improvement

### PR DESCRIPTION
**Pull request by tiagofreire-pt**
For the RV3028 RTC, the definitions for its `backup-switchover-mode` overlay where not intelligible neither complete/exhaustive.

Accordingly to the https://github.com/raspberrypi/linux/issues/2912#issuecomment-477670051, these should be correct.

### CODE REVIEW

**Comment by tiagofreire-pt** [comment]
`/boot/config.txt` should be:

Configurating example, for rv3028, on a Uputronics GPS Extension HAT:
```
# For GPS Expansion Board from Uputronics
dtparam=i2c_arm=on
dtoverlay=i2c-rtc,rv3028,backup-switchover-mode=3
dtoverlay=pps-gpio,gpiopin=18
init_uart_baud=115200```

**Comment by tiagofreire-pt** [comment]
From my tests (`sudo i2cget -y 1 0x52 0x37`):

`Default from factory`: `0x10`

`Mode 0`: `0x10`

`Mode 1`: `0x14`

`Mode 2`: `0x18`

`Mode 3`: `0x1c`

**Comment by tiagofreire-pt** [comment]
`Mode 3`: `0x1c` is consistent with the manufacturer configuration script: http://store.uputronics.com/files/configure-rv3028.sh

**Comment by pelwell** [comment]
The README content looks reasonable, but it needs to patched at source - in our Linux repo: https://github.com/raspberrypi/linux

**Comment by tiagofreire-pt** [comment]
> The README content looks reasonable, but it needs to patched at source - in our Linux repo: https://github.com/raspberrypi/linux

Done, as requested: https://github.com/raspberrypi/firmware/pull/1861

Thanks.

**Pull request closed without merging**
