### PR TITLE
Add a script to generate the file to submit to the LVFS

### PR DESCRIPTION
**Pull request by hughsie**
The LVFS site https://beta-lvfs.rhcloud.com/ accepts and mirrors .cab files and
new versions of fwupd can update the firmware on the Raspberry Pi automatically.

### CODE REVIEW

**Comment by popcornmix** [comment]
I'm not sure if having these files in everyone's /boot directory makes sense. That will likely cause confusion to the average user.

Currently you can update firmware with apt-get upgrade or rpi-update. These can support separate testing branches, and you can revert to any historical firmware to identify regressions.

Can you explain the benefit a new scheme adds to this?

**Comment by hughsie** [comment]
Hi,

I don't think it makes sense to actually install the .inf or .metainfo.xml files onto the RPi device itself, they're really only for firmware engineers like yourself or keen helpers like me. If it would help, I could move these to a toplevel "contrib" or "scripts" directory if you're just using a glob to install things from boot/*

I'm aware you need a lot more information about this before you'll consider merging, so my PR is more of a starting point for discussion. Some more background: fwupd is a mechanism for updating various different firmware files on devices ranging from ARM tablets to high-end infiniband server-class PCI hardware. It's designed to be a standard interface for querying the firmware version installed on devices, and more importantly to *automatically* and securely update firmware if the user has enabled this on the system.

To be able to show a useful GUI, we also need to show some user-visible text about the update, so we can do things like http://people.freedesktop.org/~hughsient/temp/Screenshot%20from%202015-07-28%2012-14-31.png and also show a useful command line interface. This allows people to see what is updated and *why* they should update. This is more and more important as some firmware for some devices will be fixing security issues rather than adding hardware support.

The basic idea is that the person building new firmware (you?) also fills in a couple of lines of text in the metainfo.xml file with a user-facing description of what was fixed in the new version. Then someone would run a script which packages up boot/* and builds a .cab file which can be submitted to https://beta-lvfs.rhcloud.com/

Every day, clients query the metadata at beta-lvfs.rhcloud.com and if the hardware ID matches then the firmware is downloaded, checksum compared and GPG signature checked. This is applied to the hardware using a device-specific provider, for instance https://github.com/hughsie/fwupd/blob/master/src/fu-provider-rpi.c in the case of the RPi.

Now, I'm aware I'm asking you to do extra work for each release, and I'm totally happy running the script myself and submitting the file to LVFS after important bug fixes, but I'm also happy giving you the vendor-key and letting you do this yourself. RPi is an important project for us, so I'm happy to help as much as required.

We're intending to roll out fwupd to RHEL and Fedora really soon, and require all our hardware partners to support this. Obviously this kind of certification isn't so interesting for the RPi, but it would be awesome to have it treated as a first class citizen and to get automatic firmware updates when it's being used as a desktop machine.

Comments, questions or queries most welcome. Thanks!

**Comment by popcornmix** [comment]
So is there anything stopping you doing that automatically now?
E.g. have a script that runs once a day, and checks if head of https://github.com/raspberrypi/firmware has changed.
If it has changed, check out latest files and create the .cab file. You can use the github commit message as the description.

**Comment by hughsie** [comment]
You're right, nothing is stopping me doing this now, but there are three points to consider:

* The commit message is the technical fix, i.e. "kernel: Fix SPI communication to elantech.ko module" and the metainfo file needs a high level end-user message, e.g. "Make Elantech screens work".

* I don't want any legal issues, although I think in this case the firmware is redistributable as long as it's being used on the RPi so I should be fine

* I don't really want to submit new firmware every day; batching this up manually means you can chose to do an upload after a significant fix or when a large number of people are going to be helped.

**Comment by popcornmix** [comment]
We have two main sources of firmware updates.
rpi-update for the bleeding edge testers
apt-get upgrade for the more stable updates

rpi-update tends to have one or two updates a week.
apt-get tends to be updated after a month or two. 

My previous message describes the first scheme. For the second scheme you could test http://archive.raspberrypi.org/debian/ for an update to the firmware package which would produce much less frequent updates.

**Comment by hughsie** [comment]
If you don't mind me asking, how do you decide when to push out a new stable firmware out via apt-get?

**Comment by popcornmix** [comment]
It might be if a significant bug has been fixed.
Normally it's when a new sdcard image has been produced (e.g. with updates to the default packages), we make a decision whether to bump to the top of tree firmware/kernel, or perhaps pick a version from a week or two back that we believe doesn't have any outstanding regressions.

**Comment by hughsie** [comment]
Do you tag the commit in some way? Or is there some way to be notified when you decide to push out an apt-get update? I'm happy to arrange a script to do this if there's an easy way of automating it. It might be easier for you guys to submit the new .cab file to the LVFS site in this case, although I appreciate this adds a couple of minutes to your release process.

**Comment by popcornmix** [comment]
Not currently. There are schemes to determine the git hash of the firmware from an installed firmware package.
However it has been requested a few times, so we'll try to get a tag added when producing the next firmware (apt) package update.

**Comment by hughsie** [comment]
>There are schemes to determine the git hash of the firmware from an installed firmware package.

I found this for https://github.com/hughsie/fwupd/blob/master/src/fu-provider-rpi.c#L105 -- I used the yyyymmdd data as the firmware version as this was certain to only go up.

**Comment by Ruffio** [comment]
@popcornmix is this PR going to be merged or should it be closed?

**Comment by popcornmix** [comment]
No it won't be merged.

**Pull request closed without merging**
