### PR TITLE
New readme

### PR DESCRIPTION
**Pull request by Bengt**
GitHubified the README for reader's convenience.

### CODE REVIEW

**Comment by Ruffio** [comment]
Is this going to be merged?

**Comment by popcornmix** [comment]
If @Bengt want to rebase and squash the commits it can probably be merged.

**Comment by Ruffio** [comment]
@Bengt would you rebase and squash the commits, so it can be merged?

**Comment by Bengt** [comment]
Sorry, I had a look at the changes and no, they can not be easily rebased.
This is due to the fact, that they affect most of the file and many new
changes were made to it in the meantime. So the only way I see is to work
with the current version and transform it into proper markdown manually.
That also seemed tedious, so I gave up on this. Maybe some else wants to
give it a try. Should we abandon and close this pull request?

2016-06-27 10:42 GMT+02:00 Rasmus Christiansen <notifications@github.com>:

**Pull request closed without merging**
